server {
    listen 80;

    # Servir archivos de Angular
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Redirigir llamadas de Auth Service
    location /api/auth/ {
        proxy_pass http://auth-service:8080/api/; 
        proxy_set_header Host $host;
    }

    # Redirigir llamadas de Business Service
    location /api/business/ {
        proxy_pass http://business-service:8080/api/;
        proxy_set_header Host $host;
    }
}